/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.genix

import kotlin.test.Test
import kotlin.test.assertTrue
import kotlin.test.assertFalse

class AppTest2 {
    @Test fun testTrueIsTrue() {
        assertTrue(true)
    }

    @Test fun testFalseIsFalse() {
        assertFalse(false)
    }
}
